config/routes.rb
Rails.application.routes.draw do

  root :to => "home#index"
  resources :users do
    resources :activities
  end

  get 'track' => 'activities#track'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit]

  def index
    @activities = Activity.where(user_id: params[:user_id])
    @miles = @activities.sum(:length)
  end

  def show
  end

  def new
    @user = User.find(params[:user_id])
    @activity = Activity.new(:user_id=>params[:user_id])
  end

  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to user_activities_path, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  def track
    @miles = params[:miles]
    puts @miles
    puts "up here?"
    @miles
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:sport, :user_id, :length)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_form.html.erb
<%= form_for([@user, @activity]) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sport %><br>
    <%= f.text_field :sport %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.text_field :length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', user_activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Activities</h1>

<table>
  <thead>
    <tr>
      <th>Sport</th>
      <th>Length</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.sport %></td>
        <td><%= activity.length %></td>
      </tr>
    <% end %>

  </tbody>


</table>
<tr>Total miles: <%= @miles %></tr>


<br>
<%= link_to "Track Your Fitness!",
            :controller => "activities",
            :action => "track", :miles => @miles %>

<br>

<%= link_to 'New Activity', new_user_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', user_activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>
<h2> </h2>

<p>
  <strong>Sport:</strong>
  <%= @activity.sport %>
</p>

<p>
  <strong>Length:</strong>
  <%= @activity.length %>
</p>

app/views/activities/track.html.erb
<style>
  html, body {
    margin-top: 50px;
    height: 300px;
  }
  #map {
    height: 400px;
    width: 100%;
  }
</style>
<body>

<p>You're combined fitness activity of <%= @miles %> miles was equivalent to driving from point A to B.</p>

<div id="map" data-miles="<%= @miles %>"></div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBpZRx8EZifeUhcyW6Yne_M5tWuAthDZ_I&callback=gps.showMap"
        async defer></script>
</body>

app/views/home/index.html.erb
<div id="bgimage">
  <div class="overlay">
    <h1 class="title">Fitness Tracker</h1>
    <h2>Ever wonder how far you have traveled in a week of fitness activity?</h2>
    <p>Input your fitness activity- the sport and length in miles you were active. Make sure to log the distance in miles you worked out for each activity!</p>
    <p>Then select 'Track' to see how far you've traveled in total for that week! Fitness Tracker calculates the total distance and shows you the destination you would have reached.</p>
  </div>
</div>

app/views/layouts/_formnav.html.erb
<li><a href="/">Home</a></li>
<li><a href="/users">Track</a></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FitnessTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="navbar">
  <div id="pushnav">
    <ul>
      <%= render :partial => 'layouts/formnav' %>
    </ul>
  </div>
</div>

<div style="margin-top: 50px ">
<%= yield %>
</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Users</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name.capitalize %></td>
        <td><a href="/users/<%= user.id %>/activities">Activities</a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2>User</h2>
<p>
  <strong>Name:</strong>
  <%= @user.name.capitalize %>
</p>

<br>
<a href="<%= @user.id %>/activities">Activities</a>
<br>
<%= link_to 'Back to Users', users_path %>